# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7632504d347b050ae4b13e0768aa7a5a88ee20bb158a47416eeae4a4e0663091ccb318d2c18c0f660b4796ea96d31c7191c4383b9a7f7ab3ce88a51ff6103649

test:
  secret_key_base: 90e18bed55a26b9693110329942383ddcfbcf25dde690e10cb0f6a3223e8e84949c57147832c438f4dd20d3f76c7a9a0f7806264c90ccd9e9f3f89eb85ef6c0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
